version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  microservice.jobscheduler:
    image: ${DOCKER_REGISTRY-}microservicejobscheduler
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Microservice.JobScheduler/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;User Id=DockerUser;Password=DockerUser;Initial Catalog=Jobscheduler;MultipleActiveResultSets=true;TrustServerCertificate=true;
   
  microservice.taskqueuemanager:
    image: ${DOCKER_REGISTRY-}microservicetaskqueuemanager
    depends_on:
      - rabbitmq
      - microservice.jobscheduler
    build:
      context: .
      dockerfile: Microservice.TaskQueueManager/Dockerfile
    volumes:
      - "E:/:/mnt/e"
   

